### ISSUE TITLE
Percentage issue

### ISSUE THREAD

**Issue by sergeevabc** [VladimirMarkelov/rclc#2]
Dear Vladimir,
I am trying to calculate as follows
```console
$ rclc 130-20%
ERROR: Too many operators
```
However, other CLI calculators such as [Qalc][1] output 104 as expected.

[1]: https://github.com/Qalculate/libqalculate/releases/

**Comment by VladimirMarkelov** [comment]
Thanks for reporting the issue. Yes, rclc does not support percentage yet. I use parsing without look ahead that makes impossible to distinguish between `10 % 2` and `10 + 2 %` - so, the parser thinks that in both cases `%` is a modulo operation. I think I can add a per-calculation step to add `%` support. The only trouble is to interpret cases correctly. As of these ones, it is clear:

`a + b %` = increase `a` by `b` percents
`a - b %` = decrease `a` by `b` percents

these ones are kind of clear but maybe not obvious:

`a * b %` = calculate `b` percent of `a`
`a / b %` = calculate how many percents is `b` of `a` (e.g, `10 / 5 % == 200` because `10` is twice bigger than `5`)

the last example is questionable but I do not know a better usage for division and percent signs together.

What to do for the other combinations? Throw an error at least at this moment? I am talking about cases like `a & b %`, `a << b %` and so on.

Another question is `%` priority. I do not like how it is done in Qalc:

`10 - 20 + 4%` is calculated as `(10-20)+4%`. I think, I'd prefer `10- (20 + 4%)` way. In other words, always stick `%` to the closest value.

**Comment by sergeevabc** [comment]
@VladimirMarkelov, Qalc behaves here as a classical Windows Calc, i.e. step by step: a) 10-20=-10, b) -10+4%=-10,4
Off-line hand-held Citizen calculator behaves the same way. If one wants another order, parentheses should be used.
Let’s proceed step by step as well, i.e. implement addition and subtraction first, then we’ll see.

**Comment by VladimirMarkelov** [comment]
I've added `%` as a percentage:

```
    a + b % - increase the number a by b percents
    a - b % - decrease the number a by b percents
    a * b % - calculate b percent of a (short for a * b / 100)
    a / b % - calculate how many percents is a of b (short for a / b * 100)
```

docs updated as well. If it looks good I'll add a new tag and publish new version.

**Comment by sergeevabc** [comment]
I rarely use multiplication and division with percentages,
but am ready to test addition and subtraction as soon as
Windows binary is ready.

**Comment by VladimirMarkelov** [comment]
I agree: multiplication and division with percentages are rare cases, but as I tried qCalc supports at least multiplication. I do not think it hurts adding both.

Pre-release: https://github.com/VladimirMarkelov/rclc/releases/tag/0.8.9-rc1

If it is OK (just close the issue if it is OK), I'll add a tag and rename the release title.

**Comment by sergeevabc** [comment]
Entering data literally with spaces as the documentation says does not work,
i.e. `rclc.exe 100 + 10 %` = 100 (Qalc works here).

Let's try w/o spaces. Now it works, but the output looks inconsistent as follows
`rclc.exe 100+20%` = 120, but `rclc.exe 100+10%` =  110._00000000000002_

**Comment by VladimirMarkelov** [comment]
Thanks a lot! It was an old bug when the calculator used only the first argument. Now it takes all of them. So, in the previous version only `rclc "100 + 10 %"` worked.

Updated: https://github.com/VladimirMarkelov/rclc/releases/tag/0.8.9-rc2

Edit: percentage seems more accurate now. The same release tag updated.

**Comment by sergeevabc** [comment]
Recently I found [Kalker][1], another CLI calculator written in Rust with percentages support.
I shall use it further along with Qalc (written in C++) to compare calculation results.
Now, let us add one more calculation step as follows to catch a discrepancy: -10.4 vs -10.8.

```console
$ qalc 10 - 20 + 4%
(10 - 20) * (104 * percent) = -52/5 = -10,4 

$ kalker 10 - 20 + 4%
-10.4

$ rclc 10 - 20 + 4%
-10.8
```

[1]: https://kalker.strct.net/

**Comment by VladimirMarkelov** [comment]
Aha. So, at least two calculators set priority for `%` as low as `+` and `-`. I'll change it. Now `rclc` also shows `-10.4` in this case.

https://github.com/VladimirMarkelov/rclc/releases/tag/0.8.9-rc3

**Comment by sergeevabc** [comment]
It seems `rclc` does not like when expression begins with minus, interpreting it as a switch instead,
so `rclc -10.5*10.5+10.5%` and `rclc "-10.5*10.5+10.5%"` fail, but `rclc (-10.5*10.5+10.5%)` works.

**Comment by VladimirMarkelov** [comment]
Good catch! It seems a library that parses the command line swallows all items starting with `-` and treats them as options. I'll check if I can extract unused options to treat then as an expression

**Comment by VladimirMarkelov** [comment]
https://github.com/VladimirMarkelov/rclc/releases/tag/0.8.9-rc4

Now `rclc -10.5*10.5+10.5%` should work
